version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  api:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=basegun.settings.development
      - POSTGRES_PASSWORD=exemple
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
