version: '3.7'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  api:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=basegun.settings.development
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - S3_URL_ENDPOINT=http://minio:9000
      - S3_BUCKET_NAME=basegun-s3
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - WORKSPACE=local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  adminer:
    image: adminer
    ports:
      - 7081:8080
