# Generated by Django 5.0.3 on 2024-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.DecimalField(decimal_places=9, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_identifier', models.CharField(max_length=255)),
                ('assignment_service', models.CharField(max_length=255)),
                ('agent_phone_number', models.CharField(max_length=16)),
                ('agent_email', models.EmailField(max_length=254)),
                ('weapon_type', models.CharField(max_length=255)),
                ('weapon_length', models.IntegerField()),
                ('weapon_barrel_length', models.IntegerField()),
                ('picture_left', models.FileField(upload_to='')),
                ('picture_right', models.FileField(upload_to='')),
                ('picture_markings', models.FileField(upload_to='')),
                ('picture_charger', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
