# Generated by Django 5.0.1 on 2024-02-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_identifier', models.CharField(max_length=255)),
                ('assignment_service', models.CharField(max_length=255)),
                ('agent_phone_number', models.CharField(max_length=16)),
                ('agent_email', models.EmailField(max_length=254)),
                ('seizure_date', models.DateField(max_length=255)),
                ('weapon_type', models.CharField(max_length=255)),
                ('weapon_length', models.IntegerField()),
                ('weapon_barrel_length', models.IntegerField()),
                ('picture_left', models.FileField(upload_to='')),
                ('picture_right', models.FileField(upload_to='')),
                ('picture_markings', models.FileField(upload_to='')),
                ('picture_charger', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
