# Generated by Django 5.0.2 on 2024-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='confidence',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
