# Generated by Django 5.0.2 on 2024-02-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_analysis_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='seizure_date',
        ),
    ]
