name: Continuous integration 
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/datalab-mi/basegun-backend:${{ github.ref_name }}
  
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: ghcr.io/datalab-mi/basegun-backend:${{ github.ref_name }}
      env:
        WORKSPACE: dev
        AWS_REGION: gra
        AWS_DEFAULT_REGION: gra
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_URL_ENDPOINT: https://s3.gra.io.cloud.ovh.net/
        S3_BUCKET_NAME: basegun-s3
        POSTGRES_PASSWORD: postgres
    steps:
      - run: cd /code && pytest
